---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app
  namespace: flux-app
  labels:
    app: flux-app
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-app
  strategy: {}
  template:
    metadata:
      labels:
        app: flux-app
    spec:
      containers:
      - name: flux-app-container
        image: bibhas2/gitops-demo-webapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flux-app-service
  labels:
    app: flux-app-service
spec:
  selector:
    app: flux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

